title: YoungChanYoo
description: Security Engineer
short_bio: "다양한 프로젝트에서 시스템 설계와 구현을 통해 문제를 해결하며 보안 역량까지 확장하고 있는 신입 엔지니어입니다."
site_title: '@YoungChanYoo-portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Personalization
github_username: wasd132
blog_url: 
email: wasd13579@gmail.com
phone: 010-7502-3370
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 

# Rebuild trigger: 2026-02-25 01:25 UTC
